# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Name',
            field=models.TextField(default='Mike'),
        ),
    ]
